### PR TITLE
Run commands in vscode terminal with full path to CLI

### LINKED ISSUE #92: Run CLI commands using the full path to the stripe binary instead of using the word `stripe`
We are running CLI commands using the `stripe` command. This could fail if a user has aliases or symlinks set up in an unorthodox or unforeseen way. We should use the user's absolute path to their stripe binary when invoking CLI commands. There is already logic in `stripeClient.ts` for finding the path.

### PR DESCRIPTION
**Pull request by vcheung-stripe**
### Notify
cc @stripe/developer-products 

### Summary
Instead of using the string `stripe`, use the full path to the CLI executable to run Stripe commands in the vscode terminal. We already use this path when detecting if the user has the CLI installed. This also means our commands will use the user's `stripe.cliInstallPath` setting if they set a custom path.

To achieve this, we made `StripeTerminal` depend on `StripeClient` and added a public method to `StripeClient` to get the CLI path.

Screenshots:
Screen Shot 2021-01-28 at 4 10 00 PM
Clicked **Start API logs streaming**; default path was used.

Screen Shot 2021-01-28 at 4 10 50 PM
Clicked **Start API logs streaming**; custom path was used.

Screen Shot 2021-01-28 at 4 11 39 PM
Clicked **Start API logs streaming** but CLI wasn't installed; prompt for install.

Screen Shot 2021-01-28 at 4 11 12 PM
Clicked **Start API logs streaming** but CLI wasn't at custom path; show error message.

Screen Shot 2021-01-28 at 4 12 22 PM
A user can still listen for events and stream logs simultaneously.

### Motivation
Fixes #92 

### Testing
- Added tests to check that the `StripeTerminal` class will run commands with `/usr/local/bin/stripe` or a custom path
- Updated tests for `StripeClient` to reflect its new public interface
- Manually verified; see screenshots

### CODE REVIEW

File: src/stripeTerminal.ts [hunk 1]
```diff
@@ -25,17 +28,22 @@ export class StripeTerminal {
     command: SupportedStripeCommand,
     args: Array<string> = [],
   ): Promise<void> {
+    const cliPath = await this.stripeClient.getCLIPath();
+    if (!cliPath) {
```
Comment (gracegoo-stripe) [inline src/stripeTerminal.ts:32]: I was gonna suggest we prompt the user if this happens but it looks like we already do that from getCLIPath() -> detectInstalled()!

**Review by gracegoo-stripe — APPROVED** [review]
